# -*- coding: utf-8 -*-
"""Final_Project_NYPD_Arrest_Covid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NIYKsBuxiXftkcIxAqkmi4axp6yrwIY4

##Felony-based Arrests in New York City during COVID-19 Pandemic in 2020##

[NYPD report](https://www1.nyc.gov/site/nypd/news/p0106a/overall-crime-new-york-city-reaches-record-low-2020) shows that the overall crime in New York City reaches record low in 2020 during the pandemic. However, at the same time, NYPD also stressed that such decrease of crime rate is accompanied by significant upticks in homicides, shootings, burglaries and car thefts. A [New York Times article](https://www.nytimes.com/2020/12/29/nyregion/nyc-2020-crime-covid.html) points out that, the increased crime cases, such as shootings have doubled, and most of them were concentrated in the areas hardest hit by the coronavirus and unemployment. 

According to the ["COVID-19 Data by ZIP Code"](https://www1.nyc.gov/site/doh/covid/covid-19-data-totals.page#zip) released by the health department, Staten Island, Bronx and Queens are the three boroughs that got most seriously hit by the disease (rate per 100,000 people).

In this project, I am going to focus on NYPD's record of **arrests on felony counts** in New York City during the height of pandemic (March - December 2020). Though arrest does not necessarily lead to judiciary crime, NYPD's arrest record provides us a relatively comprehensive account to see the immediate changes in the city during the pandemic.

**My research questions are:** 

*   Did New York City show an increased number of arrests on felony counts during the pandemic in 2020? 
*   What types of arrests on felony counts were mostly recorded?
*   Who were arrested on those felony counts? (demographic characteristics) 
*   Where did those arrests on felony counts usually happen?
*   Does the location of those arrests on felony counts correspondent to the areas most seriously hit by the pandemic?


The datasets I am going to rely on include:

[NYPD Arrests Data (Historic)](https://data.cityofnewyork.us/Public-Safety/NYPD-Arrests-Data-Historic-/8h9b-rp9u) 

[NYPD precinct map](https://data.cityofnewyork.us/Public-Safety/Police-Precincts/78dh-3ptz)

[COVID-19 Data by Date](https://www1.nyc.gov/site/doh/covid/covid-19-data.page#epicurve)


It is also important to note that, the NYPD arrest record inevitably shows establishment institutional bias.

### Set the Stage ###
Before we proceed the project, we mount our drive which usually contains the datasets we need. We also need to import the modules that are necessary for the project.
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np

# %pip install --upgrade --quiet plotly
import plotly.express as px

import plotly.graph_objects as go
from plotly.subplots import make_subplots

import requests

"""### Retrieve NYPD Arrest Data ###
NYC open data allows us to download the [NYPD arrest dataset](https://data.cityofnewyork.us/Public-Safety/NYPD-Arrests-Data-Historic-/8h9b-rp9u). For the purpose of this project, we first need to filter the data according to the time-span needed: March 1 - December 31, 2020, when New York City was mostly seriously hit by the epidemic. 

Then we download the dataset as .csv file and load the dataset for further process.  
"""

url_2020 = '/content/drive/MyDrive/Colab Notebooks/NYPD_Arrests_Data__2020mar-dec.csv'
df_20 = pd.read_csv(url_2020)
df_20

"""### NYPD Arrest in 2020 ###

Before we do any comparison or calculation, we can browse through the data to get a first impression. According to the NYPD Arrest record dictionary, we may be interested in the fields of "ARREST_Date", ""OFNS_DESC"(offense description), "LAW_CAT_CD"(category of arrest type, such as felony, misdemeanor), "ARREST_PRECINCT", "AGE_GROUP", "PERP_SEX", and "PERP_RACE".
"""

# modify the arrest date to yyyy-mm-dd format.

df_20['ARREST_DATE'] = pd.to_datetime(df_20['ARREST_DATE'], format='%m/%d/%Y')
df_20

"""Now we can get the information about the daily counts of arrests based on different reasons, including felony (LAW_CAT_CD as F), misdemeanor (M), violation (V), and others (I)."""

crime_type = df_20.groupby(['LAW_CAT_CD'])
crime_counts_day = crime_type.resample('D', on='ARREST_DATE').size().reset_index(name='day_counts')
crime_counts_day

"""What about we show the daily counts in a line graph?"""

fig = px.line(crime_counts_day,x='ARREST_DATE',y='day_counts', color='LAW_CAT_CD',title='Arrest Types During Covid by Day 2020')
fig.show()

"""The above figure shows the daily counts of arrests on different reasons. We can see the number of arrests on felony and misdemeanor reasons is much higher than the other two.

But this daily count figure is too flucturating to show a clear picture of the trend.

Perhaps a weekly count of arrest records could give us a clearer picture? Let's try. 
"""

crime_counts_week_20 = crime_type.resample('W', on='ARREST_DATE').size().stack().reset_index(name='week_counts')
crime_counts_week_20

fig = px.line(crime_counts_week_20,x='ARREST_DATE',y='week_counts', color='LAW_CAT_CD',title='Arrest Types During Covid by Week 2020')
fig.show()

"""Hmmmm, this figure of weekly arrest count is much clearer, showing that the number of arrests on felony and misdemeanor counts increased sharply at the beginning of the pandemic, which was March and April in 2020.

But did the number of arrests, especially on felony counts, increased a lot compared to 2019 as the New York Times article claimed?

### NYPD Arrest in 2019 ###

Now let's take a look at the dataset in 2019 (also March - December).

We can go to the same NYC open data website and retrieve the 2019 NYPD arrest dataset by using the same method, while filtering the data according to the new time-span.
"""

url_2019 = '/content/drive/MyDrive/Colab Notebooks/NYPD_Arrests_Data__2019mar-dec.csv'
df_19 = pd.read_csv(url_2019)
df_19

df_19['ARREST_DATE'] = pd.to_datetime(df_19['ARREST_DATE'], format='%m/%d/%Y')
df_19

"""Similarly, we get the weekly count of arrest records in 2019."""

crime_type_19 = df_19.groupby(['LAW_CAT_CD'])
crime_counts_week_19 = crime_type_19.resample('W', on='ARREST_DATE').size().reset_index(name='week_counts_19')
crime_counts_week_19

"""### NYPD Arrest 2019-2020 Comparison ###

To answer our question about whether or not felony-reasoned arrests increased in 2020 during the pandemic, we now focus on the number of arrests based on felony suspicion.

Let's get the weekly number of felony-reasoned arrests in 2019 and 2020 respectively.
"""

crime_counts_week_20_felony = crime_counts_week_20[crime_counts_week_20['LAW_CAT_CD'] == 'F']
crime_counts_week_20_felony

crime_counts_week_19_felony = crime_counts_week_19[crime_counts_week_19['LAW_CAT_CD'] == 'F']
crime_counts_week_19_felony

"""For better viewing, we can merge the weekly felony-reasoned arrest numbers in 2020 and 2019 together.

The default index here can serve as the indicator of number of week, e.g. 1 means Week1. 
"""

crime_counts_comp_felony = crime_counts_week_20_felony.merge(crime_counts_week_19_felony, how='left', left_index=True, right_index=True)
crime_counts_comp_felony = crime_counts_comp_felony.rename(columns={"week_counts": "week_counts_20"})
crime_counts_comp_felony

"""Now let's see how the number of felony-reasoned arrests changed in 2020 in comparison to 2019.

"""

crime_counts_comp_felony['change_percentage'] = (crime_counts_comp_felony['week_counts_20'] - crime_counts_comp_felony['week_counts_19'])/crime_counts_comp_felony['week_counts_19']*100
crime_counts_comp_felony

"""Hmmm, interestingly, results show that, actually, the weekly felony-reasoned arrests during the pandemic in 2020 most likely decreased (minus percentage) compared to the same period in 2019.

To visualize the 2019-2020 comparison, let's make a line graph.
"""

crime_counts_comp_felony['time_stamp'] = crime_counts_comp_felony.index
crime_counts_comp_felony

time_stamp = crime_counts_comp_felony['time_stamp']
week_counts_19 = crime_counts_comp_felony['week_counts_19']
week_counts_20 = crime_counts_comp_felony['week_counts_20']

# Create figure with secondary y-axis
fig = make_subplots(specs=[[{"secondary_y": True}]])

# Add traces
fig.add_trace(
    go.Scatter(x=time_stamp, y=week_counts_19, name='weekly felony-reasoned arrests 2019'),
    secondary_y=False,
)

fig.add_trace(
    go.Scatter(x=time_stamp, y=week_counts_20, name='weekly felony-reasoned arrests 2020'),
    secondary_y=True,
)

# Add figure title
fig.update_layout(
    title_text='Felony-reasoned Arrest Weekly Count 2019-20 Comparison'
)

# Set x-axis title
fig.update_xaxes(title_text="Week")

# Set y-axes titles
fig.update_yaxes(title_text="weekly felony-reasoned arrests 2019", secondary_y=False)
fig.update_yaxes(title_text="weekly felony-reasoned arrests 2020", secondary_y=True)

fig.show()

"""Now we know that according to NYPD arrest records, the number of felony-reasoned arrests (by weekly counts) in 2020 actually decreased compared to that of 2019.

### Closer Look at NYPD Arrest 2020 ###

Let's take a closer look at the arrest records in 2020.

We want to know, among the arrests based on felony counts, what were the specific reasons.

First, we filter out the felony-reasoned arrest based on "LAW_CAT_CD" as "F".
"""

df_20_felony = df_20[df_20['LAW_CAT_CD'] == 'F']
df_20_felony

df_20_felony['OFNS_DESC'].unique()

"""We can get the counts of felony-reasoned arrests based on different reasons.

From the table below, we can see during pandemic in 2020, most NYPD ***felony-reasoned arrest*** cases were counted on **felony assult**, followed by **miscellaneous penal law**, **robbery** and **burglary**.
"""

df_20_felony_type = df_20_felony.groupby('OFNS_DESC').size().reset_index(name='counts')
df_20_felony_type.sort_values('counts', ascending=False)

"""What about arrests based on misdemeanor reasons? Let's take a look at the data as well."""

df_20_mis = df_20[df_20['LAW_CAT_CD'] == 'M']
df_20_mis

df_20_mis['OFNS_DESC'].unique()

"""From this table, we can see during pandemic in 2020, most NYPD ***misdemeanor-reasoned arrest*** cases were about **assult (degree 3) and related offenses**, **petit larceny** and **dangerous drugs**."""

df_20_mis_type = df_20_mis.groupby('OFNS_DESC').size().reset_index(name='counts')
df_20_mis_type.sort_values('counts', ascending=False)

"""We also want to know the demographic characteristics of those being arrested on felony counts. Unsurprisingly, black is the race that tops in the counts. Historically, police force is known for racial profiling."""

df_20_felony_race = df_20_felony.groupby(['PERP_RACE']).size()
df_20_felony_race.sort_values(ascending=False)

"""And the demographic characteristics of misdemeanor-based arrests is not much different, with black people tops in the counts."""

df_20_mis_race = df_20_mis.groupby(['PERP_RACE']).size()
df_20_mis_race.sort_values(ascending=False)

"""What about perpetrators' sex? Again, without much surprise, the number of male is significantly higher than female. The situation is as the same as in misdemeanor-based arrests."""

df_20_felony_sex = df_20_felony.groupby(['PERP_SEX']).size()
df_20_felony_sex.sort_values(ascending=False)

df_20_mis_sex = df_20_mis.groupby(['PERP_SEX']).size()
df_20_mis_sex.sort_values(ascending=False)

"""What about perpetrators' age? According to the results, for felony-reasoned arrests, most perpetrators fall into 25-44 age group. For misdemeanor-reasoned arrests, the same result applies."""

df_20_felony_age = df_20_felony.groupby(['AGE_GROUP']).size()
df_20_felony_age.sort_values(ascending=False)

df_20_mis_age = df_20_mis.groupby(['AGE_GROUP']).size()
df_20_mis_age.sort_values(ascending=False)

"""We can see that those being arrested based on felony and misdemeanor reasons were mostly black male aged 25-44.

### Arrest and Region ###

Now let's take a look at where did felony-reasoned arrests mostly take place.
"""

df_20_felony_boro = df_20_felony.groupby(['ARREST_BORO']).size().reset_index(name='counts')
df_20_felony_boro.sort_values('counts', ascending=False)

"""From the above table, we can see those felony-based arrests took place mostly in Brooklyn (K), followed by Manhattan (M), Queens (Q), Bronx (B), and Staten Island (S).

### Arrest and Covid-19 ### 

Let's see if the number of felony-reasoned arrest corresponded to the level of seriousness caused by Covid-19 in different boroughs

The [data of Covid-19](https://www1.nyc.gov/site/doh/covid/covid-19-data.page#epicurve) could be retrieved via the nyc.gov. The data shows the situation of Covid-infection day-by-day in different boroughs.
"""

df_covid_date = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/covid-data-by-day.csv')
df_covid_date

df_covid_date['date_of_interest'] = pd.to_datetime(df_covid_date['date_of_interest'], format='%m/%d/%Y')
df_covid_date

"""In order to correspond to the NYPD arrest dataset, here for the Covid dataset we also select the date range within March and December 2020"""

df_covid_date_2020 = df_covid_date[(df_covid_date['date_of_interest'] > '2020-2-29') & (df_covid_date['date_of_interest'] < '2021-1-1')] 
df_covid_date_2020

"""Then we focus on the Covid case numbers in different boroughs."""

df_covid_date_2020_boro = df_covid_date_2020[['date_of_interest', 'BX_CASE_COUNT', 'BK_CASE_COUNT', 'MN_CASE_COUNT', 'QN_CASE_COUNT', 'SI_CASE_COUNT']]
df_covid_date_2020_boro

"""Then we sum the Covid infection case numbers in different boroughs in year 2020

"""

print(sum(df_covid_date_2020_boro['BX_CASE_COUNT']))
print(sum(df_covid_date_2020_boro['BK_CASE_COUNT']))
print(sum(df_covid_date_2020_boro['MN_CASE_COUNT']))
print(sum(df_covid_date_2020_boro['QN_CASE_COUNT']))
print(sum(df_covid_date_2020_boro['SI_CASE_COUNT']))

"""Since the populations in different boroughs are different, we cannot simply use the total Covid case number to do comparison. Therefore, we calculate the Covid infection rate in different boroughs
We use the data from the [Census department](https://www.census.gov/quickfacts/fact/table/newyorkcitynewyork,bronxcountybronxboroughnewyork,kingscountybrooklynboroughnewyork,newyorkcountymanhattanboroughnewyork,queenscountyqueensboroughnewyork,richmondcountystatenislandboroughnewyork/PST045219) to calculate the rate (cases per 100,000 people).
"""

print(round((80385/1418207) * 100000)) #Bronx population
print(round((114977/2559903) * 100000)) #Brooklyn population
print(round((55134/1628706) * 100000)) #Manhattan population
print(round((116851/2253858) * 100000)) #Queens population
print(round((32610/476143) * 100000)) #StatenIsland population

# make a dataframe of Covid infection rate in differnet boroughs
d = {'Boro': ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'StatenIsland'], 'Covid Rate': [5668, 4491, 3385, 5184, 6849]}
df_covid_boro = pd.DataFrame(data=d)
df_covid_boro

"""In order to have a cross-comparison with the Covid infection rate, now we also need to calculate the arrest rate in different boroughs. We focus on the felony-based arrest per 100,000 population.

But before we proceed to calculation, some modification needs to be done on the NYPD data, by transforming the short-formed borough name into their fully spell-out form, for easier comprehension.
"""

def boro(row):
  if row.ARREST_BORO == 'K':
    return 'Brooklyn'
  elif row.ARREST_BORO == 'M':
    return 'Manhattan'
  elif row.ARREST_BORO == 'Q':
    return 'Queens'
  elif row.ARREST_BORO == 'B':
    return 'Bronx'
  elif row.ARREST_BORO == 'S':
    return 'StatenIsland'

# add a new column to the NYPD data which contains the full names of the boroughs

df_20_felony_boro['Boro'] = df_20_felony_boro.apply(boro, axis=1)
df_20_felony_boro

# calculate the felony-reasoned arrest rate (arrest per 100,000 population) in different boroughs based on the 2020 NYPD arrest dataset

print(round((11110/1418207) * 100000)) #Bronx population
print(round((15882/2559903) * 100000)) #Brooklyn population
print(round((11568/1628706) * 100000)) #Manhattan population
print(round((11193/2253858) * 100000)) #Queens population
print(round((2334/476143) * 100000)) #StatenIsland population

d = {'Boro': ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'StatenIsland'], 'Arrest Rate': [783,620,710,497,490]}
df_arrest_boro = pd.DataFrame(data=d)
df_arrest_boro

"""Now the felony-reasoned arrest dataset from NYPD will be merged with the Covid case by borough dataset"""

df_20_felony_covid_boro = df_arrest_boro.merge(df_covid_boro, left_on='Boro', right_on='Boro')
df_20_felony_covid_boro

"""From the table above, we can see Bronx has the highest felony-based arrest rate, while in terms of Covid infection rate, Staten Island is higher than other boroughs.

But for a clearer viewing of the order of arrest rates and Covid infection rates according to NYC boroughs, let's make bar charts.
"""

boro = df_20_felony_covid_boro['Boro']
arrest = df_20_felony_covid_boro['Arrest Rate']
covid = df_20_felony_covid_boro['Covid Rate']


fig = go.Figure()
fig.add_trace(go.Bar(x=boro, y=arrest, marker_color='rgb(0,102,204)'))

fig.update_layout(title_text='Felony-reasoned Arrest Rate in NYC Boroughs 2020')
fig.show()

"""From this bar chart, we can see the NYPD felony-reasoned arrest rate in Bronx was the highest during the pandemic period in 2020, followed by Manhattan and Brooklyn."""

fig = go.Figure()
fig.add_trace(go.Bar(x=boro, y=covid, marker_color='rgb(204,0,102)'))

fig.update_layout(title_text='Covid Infection Rate in NYC Boroughs 2020')
fig.show()

"""This bar chart shows that, the Covid infection rate in Staten Island was the highest in 2020 among other boroughs, folowed by Bronx and Queens.


From these two bar charts, we can see that **the trend of felony-reasoned arrest DOES NOT always correspondent to the serious level of Covid-infection of that borough**. While Staten Island had the highest Covid infection rate during 2020, the felony-reasoned NYPD arrest rate in that borough was actually the lowest among the other boroughs.

### Mapping Arrests ###

Now we want to know where those felony-reasoned arrests took place most, at a more granular level. Let's see the counts of felony-reasoned arrests by precinct.
"""

df_20_felony_precinct = df_20_felony.groupby(['ARREST_PRECINCT']).size().reset_index(name='counts')
df_20_felony_precinct.sort_values('counts', ascending=False)

"""With only the precinct numbers, we have no idea where did all those felony-reasoned arrests happen. A map (something like a heatmap) will certainly give a better view."""

geojson = 'https://data.cityofnewyork.us/api/geospatial/78dh-3ptz?method=export&format=GeoJSON'
response = requests.get(geojson)
response.json()

fig = px.choropleth_mapbox(df_20_felony_precinct,
                           geojson=geojson,
                           locations='ARREST_PRECINCT',
                           featureidkey='properties.precinct',
                           color='counts',
                           color_continuous_scale='oranges',
                           center = {'lat': 40.73, 'lon': -73.98},
                           hover_data=['ARREST_PRECINCT'],
                           zoom=9,
                           mapbox_style='carto-positron', title='Felony-reasoned Arrests by NY Precinct 2020')

fig.update_layout(height=650)
fig.show()

"""This map (a heat-map like) revealss a clear picture of where exactly the felony-reasoned arrests happened the most during the Covid pandemic in 2020. Precinct 75, located in Brooklyn, shows significantly darker color compared to other regions, meaning that the number of felony-reasoned arrests topped in that area. According to a [BKLYNER article](https://bklyner.com/what-will-it-take-to-fix-the-citys-most-troubled-police-precinct/), Precinct 75 (covers East New York and Cypress Hills) is historically a low-income region with noticeably high crime rate. "The NYPD’s 75th Precinct had the most gun violence incidents in the city last year", stated in the article. Ironically, this is also a precinct that is historically known for serious police corruption. And residents and community workers have been complaining about the problem of over-policing which, instead of curbs violence, but incites them. There is even a documentary [The Seven Five](https://en.wikipedia.org/wiki/The_Seven_Five) which depicts the exact issue of police misconduct. This complicated police-community dynamic worthes further study for policymakers. 

Areas west to Precinct 75 - Precincts 73 and 67 also show relatively dark organge color. 

Another area shows dark orange color is Precinct 40, in South Bronx, as well as its neighboring Precincts 44 and 46. 
"""

